# PATH CONFIG

In [1]:
import os

print(os.getcwd())
if not os.getcwd().endswith("app"):
    os.chdir("../app")
    print(os.getcwd())

import pandas as pd
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)

%load_ext autoreload
%autoreload 2
# %matplotlib inline

/home/turbotowerlnx/Documents/Master/TA/TA-Spanish-Esperanto-Translator/notebooks
/home/turbotowerlnx/Documents/Master/TA/TA-Spanish-Esperanto-Translator/app

In [2]:
from src.config import Configuration

CONFIG = Configuration(
    data_fraction=0.05
)

# EXPERIMENTS

In [3]:
def read_moses_bitext(source_path, target_path):
    """
    Reads a Moses-formatted parallel corpus from two aligned files.
    
    :param source_path: Path to the source language file (e.g., 'corpus.es')
    :param target_path: Path to the target language file (e.g., 'corpus.eo')
    :return: A list of (source_sentence, target_sentence) tuples
    """
    corpus = []
    
    with open(source_path, 'r', encoding='utf-8') as src_file, \
         open(target_path, 'r', encoding='utf-8') as trg_file:
        
        for src_line, trg_line in zip(src_file, trg_file):
            source_sentence = src_line.strip()
            target_sentence = trg_line.strip()
            
            if source_sentence and target_sentence:
                corpus.append((source_sentence, target_sentence))
    
    return corpus

In [4]:
corpus = read_moses_bitext(CONFIG.spanish_data, CONFIG.esperanto_data)

In [5]:
print(f"{len(corpus):_}")

5_750_168

In [6]:
df_corpus = pd.DataFrame(corpus, columns=["Spanish", "Esperanto"])
df_corpus.head()

,Spanish,Esperanto
0,"Se miran unos a otros, interrogándose con la m...",Ili rigardas unu la alia[n].
1,"""Sí, ¿pero en Brasil no mentirán sobre algo así?","""Jes, sed en Brazilo ili ne mensogos pri io si..."
2,"Has estado en AT5, ellos saben todo ...","Vi estis ĉe AT5, ili scias ĉion ..."
3,Dijeron el Viento y el Bosque: «¡Ninguno de lo...,"* [[1909]]: [[Elżbieta Zawacka]], pola [[kurie..."
4,"Unos a otros se miran,",Ili rigardas unu la alia[n].

In [7]:
df_corpus.sample(10)

,Spanish,Esperanto
4406382,"La niña, Adora Svitak, dice que el mundo neces...","Mirinfano Adora Svitak diras, ke la mondo bezo..."
5128842,Tenga especial cuidado con ivabradina,Antaŭite fare de Ivano Barberini
1313532,"Recubrimiento 2 d,","2a eldono,"
2459741,General Douglas MacArthur vuelve a la Filipina...,"Generalo Douglas MacArthur alteriĝas ĉe Leyte,..."
1274029,El gobierno argentino decidió sumar dos observ...,La argentina registaro decidis aldoni du meteo...
871202,Una Noche en el Roxbury (1998),Nokto ĉe la Roxbury (1998)
267103,"En nuestro juicio, que duró siete meses, estuv...","Nian proceson, kiu daŭris sep monatojn, ĉeesti..."
4556296,Jardínes en Tennesse,Konstruaĵoj en Tenesio
5233191,Vivió un instante de pánico hasta que recordó ...,"Mi suferis momenton de paniko, ĝis mi memoris,..."
4128030,Si no quieres que muera,aŭ se vi volas lin morta

In [8]:
df_corpus.to_csv(CONFIG.corpus_raw_path, index=False)

# Cleaning

### Remove weird patterns

In [9]:
wiki_pattern = r'\[\['
rows_to_drop = df_corpus['Esperanto'].str.contains(wiki_pattern, na=False)
df_corpus_cleaned = df_corpus[~rows_to_drop].copy()

print(f"Original samples: {len(df_corpus):_}")
print(f"Cleaned samples: {len(df_corpus_cleaned):_}")
print(f"Dropped samples: {len(df_corpus) - len(df_corpus_cleaned):_}")

Original samples: 5_750_168
Cleaned samples: 5_741_814
Dropped samples: 8_354

### Lowercase

In [10]:
df_corpus_cleaned = df_corpus_cleaned.apply(lambda x: x.str.lower() if x.dtype == "object" else x)
df_corpus_cleaned.head()

,Spanish,Esperanto
0,"se miran unos a otros, interrogándose con la m...",ili rigardas unu la alia[n].
1,"""sí, ¿pero en brasil no mentirán sobre algo así?","""jes, sed en brazilo ili ne mensogos pri io si..."
2,"has estado en at5, ellos saben todo ...","vi estis ĉe at5, ili scias ĉion ..."
4,"unos a otros se miran,",ili rigardas unu la alia[n].
5,tiene un significado semejante al de gehena.,"tiel ""geheno"" (minuskle) fariĝis (nuntempe eks..."

### Reduce dataset 
Due to limited computational power, reducing the amount of data that will be used

In [ ]:
df_corpus_cleaned_cropped = df_corpus_cleaned.sample(frac=CONFIG.data_fraction, random_state=CONFIG.seed)
n_total = len(df_corpus_cleaned)
n_cropped = len(df_corpus_cleaned_cropped)
print(f"Original samples: {n_total:_}")
print(f"Cropped samples: {n_cropped:_}")
print(f"Total dropped samples: {n_total - n_cropped:_}")
print(f"Total portion: {n_cropped / n_total:.2%}")

Original samples: 5_741_814
Cropped samples: 287_091
Total dropped samples: 5_454_723
Total portion: 5.00%

### Save processed corpus

In [12]:
df_corpus_cleaned_cropped.to_csv(CONFIG.corpus_path, index=False)